/**
 * MikroTik Load Balancing PCC (Per Connection Classifier) Generator
 * Supports RouterOS v6.x and v7.x
 * Developed for ComitTools Pro
 */

function generatePCCScript(config) {
    const {
        rosVersion = 'v7', // 'v6' or 'v7'
        wanList = [
            { name: 'ISP1', iface: 'ether1', gateway: '192.168.1.1', ip: '192.168.1.2/24', ratio: 1 },
            { name: 'ISP2', iface: 'ether2', gateway: '192.168.2.1', ip: '192.168.2.2/24', ratio: 1 }
        ],
        lanIface = 'bridge-lan',
        lanSubnet = '192.168.88.0/24',
        pccClassifier = 'both-addresses-and-ports', // or 'both-addresses', 'src-address'
        checkGateway = true,
        includeNat = true,
        includeDns = true,
        dnsServers = '1.1.1.1,8.8.8.8'
    } = config;

    const totalWan = wanList.length;
    let output = [];

    output.push(`# ===================================================`);
    output.push(`# MikroTik RouterOS Load Balance PCC (${totalWan} WAN)`);
    output.push(`# Target Version: RouterOS ${rosVersion.toUpperCase()}`);
    output.push(`# LAN Interface : ${lanIface} (${lanSubnet})`);
    output.push(`# Generated by  : ComitTools Pro (${new Date().toLocaleDateString()})`);
    output.push(`# ===================================================\n`);

    // 1. IP Addresses (Optional template)
    output.push(`# --- 1. WAN & LAN IP ADDRESS CONFIGURATION ---`);
    wanList.forEach((wan, idx) => {
        output.push(`/ip address add address=${wan.ip || `192.168.${idx+1}.2/24`} interface=${wan.iface} comment="${wan.name}"`);
    });
    output.push(`/ip address add address=192.168.88.1/24 interface=${lanIface} comment="LAN"\n`);

    // 2. DNS
    if (includeDns) {
        output.push(`# --- 2. DNS CONFIGURATION ---`);
        output.push(`/ip dns set allow-remote-requests=yes servers=${dnsServers}\n`);
    }

    // 3. NAT Masquerade
    if (includeNat) {
        output.push(`# --- 3. NAT FIREWALL RULES ---`);
        wanList.forEach(wan => {
            output.push(`/ip firewall nat add chain=srcnat out-interface=${wan.iface} action=masquerade comment="NAT ${wan.name}"`);
        });
        output.push(``);
    }

    // 4. Address List for Local Subnets
    output.push(`# --- 4. FIREWALL ADDRESS LIST LOCAL ---`);
    output.push(`/ip firewall address-list`);
    output.push(`add address=10.0.0.0/8 list=LOCAL_SUBNET`);
    output.push(`add address=172.16.0.0/12 list=LOCAL_SUBNET`);
    output.push(`add address=192.168.0.0/16 list=LOCAL_SUBNET\n`);

    // 5. RouterOS v7 Routing Tables
    if (rosVersion === 'v7') {
        output.push(`# --- 5. ROUTING TABLES (RouterOS v7 FIB) ---`);
        output.push(`/routing table`);
        wanList.forEach((wan, idx) => {
            output.push(`add fib name=to_${wan.name.toLowerCase()} comment="Table for ${wan.name}"`);
        });
        output.push(``);
    }

    // 6. Mangle Rules
    output.push(`# --- 6. MANGLE RULES (PCC LOAD BALANCING) ---`);
    output.push(`/ip firewall mangle`);
    output.push(`add action=accept chain=prerouting dst-address-list=LOCAL_SUBNET in-interface=${lanIface} comment="Bypass Local Traffic"`);

    // Input & Output WAN connections
    wanList.forEach(wan => {
        output.push(`add action=mark-connection chain=input in-interface=${wan.iface} new-connection-mark=${wan.name.toLowerCase()}_in passthrough=yes comment="Mark Input ${wan.name}"`);
        output.push(`add action=mark-routing chain=output connection-mark=${wan.name.toLowerCase()}_in new-routing-mark=to_${wan.name.toLowerCase()} passthrough=no`);
    });

    // PCC Classification
    output.push(`# PCC Mangle Classification`);
    wanList.forEach((wan, idx) => {
        output.push(`add action=mark-connection chain=prerouting dst-address-type=!local in-interface=${lanIface} per-connection-classifier=${pccClassifier}:${totalWan}/${idx} new-connection-mark=${wan.name.toLowerCase()}_conn passthrough=yes comment="PCC ${totalWan}/${idx} -> ${wan.name}"`);
    });

    // Mark Routing based on Connection Mark
    output.push(`# Apply Routing Marks`);
    wanList.forEach(wan => {
        output.push(`add action=mark-routing chain=prerouting connection-mark=${wan.name.toLowerCase()}_conn in-interface=${lanIface} new-routing-mark=to_${wan.name.toLowerCase()} passthrough=no`);
    });
    output.push(``);

    // 7. IP Routes
    output.push(`# --- 7. IP ROUTES (ROUTING & FAILOVER) ---`);
    const checkG = checkGateway ? ` check-gateway=ping` : '';

    if (rosVersion === 'v7') {
        output.push(`/ip route`);
        // Default Routes
        wanList.forEach((wan, idx) => {
            output.push(`add disabled=no distance=${idx+1} dst-address=0.0.0.0/0 gateway=${wan.gateway}${checkG} routing-table=main comment="Default Route ${wan.name}"`);
        });
        // Table Routes
        wanList.forEach((wan, idx) => {
            output.push(`add disabled=no distance=1 dst-address=0.0.0.0/0 gateway=${wan.gateway}${checkG} routing-table=to_${wan.name.toLowerCase()} comment="Route Table ${wan.name}"`);
        });
    } else {
        // RouterOS v6
        output.push(`/ip route`);
        wanList.forEach((wan, idx) => {
            output.push(`add distance=${idx+1} gateway=${wan.gateway}${checkG} comment="Default Route ${wan.name}"`);
        });
        wanList.forEach(wan => {
            output.push(`add distance=1 gateway=${wan.gateway}${checkG} routing-mark=to_${wan.name.toLowerCase()} comment="Route to ${wan.name}"`);
        });
    }

    output.push(`\n# ===================================================`);
    output.push(`# SCRIPT COMPLETE - PASTE TO WINBOX TERMINAL`);
    output.push(`# ===================================================`);

    return output.join('\n');
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { generatePCCScript };
}
